name: Test Newman Run

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  test-collection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Test local collection
        uses: matt-ball/newman-action@master
        with:
          collection: ./postman/postman_test_collection.json
          environment: ./postman/postman_test_environment.json
